version: "3.8"
services:
  react-app:
    # image: muinus-fe
    build: ./
    container_name: muinus-fe
    ports:
      - "3000:3000"
    restart: always
    network_mode: host

    # networks:
    #   - host
    # - muinus-network
# networks:
#   host:
#     external: true
