version: '3.8'

services:
  springboot:
    build: ./  # Backend 디렉토리에서 Dockerfile을 사용해 이미지를 빌드
    #    image: muinus-be:latest  # 미리 빌드된 이미지를 사용
    container_name: muinus-be
    restart: always
    #    depends_on:
    #      - muinus-mysql
    ports:
      - "8000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://3.39.235.66:3306/hexa
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ssafy
      SPRING_ELASTICSEARCH_REST_URIS: http://3.39.235.66:9200
      SPRING_ELASTICSEARCH_DATA_ELASTICSEARCH_REPOSITORIES_ENABLE: true
    networks:
      - muinus-network

#  nginx:
#    build: ./nginx/
#    container_name: muinus-nginx
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      #      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
#      - ./nginx/certbot/conf:/etc/letsencrypt
#      - ./nginx/certbot/www:/var/www/certbot
#    #    depends_on:
#    #      - certbot
#    networks:
#      - muinus-network
#
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./nginx/certbot/conf:/etc/letsencrypt
#      - ./nginx/certbot/www:/var/www/certbot
#    depends_on:
#      - nginx
#    networks:
#      - muinus-network

networks:
  muinus-network:
    external: true
