#spring:
#  application:
#    name: muinus
#
#  batch:
#    jdbc:
#      initialize-schema: always
#    job:
#      enabled: false
#
#    # 배치 DB
#  datasource-meta:
#    jdbc-url: jdbc:mysql://localhost:3306/hexa_batch?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    username: ssafy
#    password: ssafy
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  # 운영 DB
#  datasource-data:
#    jdbc-url: jdbc:mysql://localhost:3306/hexa?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    username: ssafy
#    password: ssafy
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
##  datasource:
##    url: jdbc:mysql://localhost:3306/hexa?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
##    username: ssafy
##    password: ssafy
##    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: none  # 운영 환경이라면 'none' 또는 'validate' 권장
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#
#  elasticsearch:
#    rest:
#      uris: http://elasticsearch:9200
#      username: your_username  # 필요 시 설정
#      password: your_password  # 필요 시 설정
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: 6fc81aea9290c3fb44078c43a90b2acb
#            redirect-uri: http://localhost:8080/api/users/kauth
#            authorization-grant-type: authorization_code
#            scope:
#              - profile_nickname
#              - account_email
#            client-name: Kakao
#            client-authentication-method: POST
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#
#  front:
#    url: http://localhost:3000
#
#jwt:
#  secretKey: t0u2eRrD1jjZV3JCLBNQKZjLjYmDb59m68WIaLRRQwvjG7NtyJk0xI92YXamsssqUQWDdQBZc62llh2ltPxPgasdaWD233wVVVZXSDQWTYDDVVFdfqww426wwdsdzxcasew3211wwadxczS22
#
#  access:
#    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
#
#  refresh:
#    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))



#spring:
#  application:
#    name: muinus
#  server:
#    port: 8000
#  front:
#    url: http://localhost:3030
#
#  # MySQL - 운영 DB
#  datasource:
#    url: jdbc:mysql://3.39.235.66:3306/hexa?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: ssafy
#    password: ssafy
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: none   # 운영 환경이라면 'none' 또는 'validate' 권장
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#
#  elasticsearch:
#    cluster:
#      name: my-cluster
#    rest:
#      uris: http://localhost:9200
#      username: your_username  # 필요 시 설정
#      password: your_password  # 필요 시 설정
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: 6fc81aea9290c3fb44078c43a90b2acb
#            redirect-uri: http://3.39.235.66/api/users/kauth
#            authorization-grant-type: authorization_code
#            scope:
#              - profile_nickname
#              - account_email
#            client-name: Kakao
#            client-authentication-method: POST
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#
#jwt:
#  secretKey: t0u2eRrD1jjZV3JCLBNQKZjLjYmDb59m68WIaLRRQwvjG7NtyJk0xI92YXamsssqUQWDdQBZc62llh2ltPxPgasdaWD233wVVVZXSDQWTYDDVVFdfqww426wwdsdzxcasew3211wwadxczS22
#
#  access:
#    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
#
#  refresh:
#    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
#
#logging:
#  level:
#    org.springframework.jdbc.datasource.init: TRACE


spring:
  application:
    name: muinus
  front:
    url: http://localhost:3030

  # MySQL - 운영 DB
  datasource:
    url: jdbc:mysql://3.39.235.66:3306/hexa?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # 운영 환경이라면 'none' 또는 'validate' 권장
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  elasticsearch:
    cluster:
      name: my-cluster
    rest:
      uris: http://3.39.235.66:9200
      username: your_username  # 필요 시 설정
      password: your_password  # 필요 시 설정
  data:
    elasticsearch:
      repositories:
        enabled: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6fc81aea9290c3fb44078c43a90b2acb
            redirect-uri: http://3.39.235.66/api/users/kauth
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

jwt:
  secretKey: t0u2eRrD1jjZV3JCLBNQKZjLjYmDb59m68WIaLRRQwvjG7NtyJk0xI92YXamsssqUQWDdQBZc62llh2ltPxPgasdaWD233wVVVZXSDQWTYDDVVFdfqww426wwdsdzxcasew3211wwadxczS22

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))

logging:
  level:
    org.springframework.jdbc.datasource.init: TRACE
